Added new Coin Link feature
CreatorCoinTools/StreamElements-ChatBot-Rally pull request #4
Opened 2021-02-01 01:36 UTC by sebasaenz

This new feature is added in response to the issue #1

2021-02-01 01:47 UTC, RallyCreatorCoins commented
@rally-ray @pashneal Can one of you please review this PR to ensure that it satisifies the requirements of #1 ? Thanks :D

2021-02-11 22:04 UTC, Ju99ernaut requested changes

2021-02-11 22:04 UTC, Ju99ernaut commented on widget.js
> +        let coinLinkHelpResponse = `To generate a custom coin link, type ${fieldData.coinLinkCommand} <CoinName> <COIN/USD> <Amount> <Memo>`;
Change `COIN` to `COINS`

2021-02-11 22:04 UTC, Ju99ernaut commented on widget.js
> +                            if (["COIN", "USD"].indexOf(coinLinkArgs[1].toUpperCase()) == -1) {
Change `COIN` to `COINS`

2021-02-11 22:50 UTC, sebasaenz commented on widget.js
> +        let coinLinkHelpResponse = `To generate a custom coin link, type ${fieldData.coinLinkCommand} <CoinName> <COIN/USD> <Amount> <Memo>`;
Done!

2021-02-11 22:50 UTC, sebasaenz commented on widget.js
> +                            if (["COIN", "USD"].indexOf(coinLinkArgs[1].toUpperCase()) == -1) {
Done!

2021-02-12 06:03 UTC, Ju99ernaut approved these changes

2021-02-12 06:04 UTC, merged